[workspace]
resolver = "2"
members = [
    "lang-core",
    "lang-optimize",
    "lang-mips",
    "rust-lang",
    "rust-macro",
    "javascript-lang",
]
exclude = []

[workspace.dependencies]
common = { git = "https://github.com/JakkuSakura/common-rs" }
