[package]
name = "fp-interpret"
version = "0.1.0"
edition = "2021"

[dependencies]
fp-core = { path = "../fp-core" }
fp-jit = { path = "../fp-jit" }
fp-native = { path = "../fp-native" }
fp-typing = { path = "../fp-typing" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
glob = "0.3"
tracing = "0.1"
eyre = "0.6"
syn = { version = "2", features = ["full"] }
num-traits = "0.2"
proc-macro2 = "1"
libffi = "5.1.0"
libloading = "0.9.0"

[dev-dependencies]
fp-lang = { path = "../fp-lang" }
