[package]
name = "fp-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
fp-backend = { path = "../fp-backend" }
fp-bytecode = { path = "../fp-bytecode" }
fp-core = { path = "../fp-core" }
fp-interpret = { path = "../fp-interpret" }
fp-lang = { path = "../fp-lang" }
fp-typing = { path = "../fp-typing" }
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.0"

[dev-dependencies]
