[package]
name = "host-struct-and-statics-host"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
path = "src/lib.rs"

[dependencies]
fp-core = { path = "../../crates/fp-core" }
fp-interpret = { path = "../../crates/fp-interpret" }

[dependencies.fp-compiler]
path = "../../crates/fp-compiler"

[dependencies.fp-lang]
path = "../../crates/fp-lang"
