#!/usr/bin/env bash

if ! (return 0 2>/dev/null); then
  echo "source scripts/activate"
  exit 1
fi

fp() {
  cargo run --release --package fp-cli --bin fp -- "$@"
}

magnet() {
  cargo run --release --package magnet --bin magnet -- "$@"
}
